### ISSUE TITLE
Exception in backend with ke_search 4.4.0 on PHP 7.4

### ISSUE THREAD

**Issue by bzgaLindner** [teaminmedias-pluswerk/ke_search#443]
Hi,

after Update to 4.4.0 (and emptying cache) I get the following error wehen opening ke-search backend module:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function Tpwd\KeSearch\Domain\Repository\IndexRepository::__construct(), 0 passed in .../xyz/typo3_src-10.4.27/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3480 and exactly 1 expected | ArgumentCountError thrown in file /abc/typo3conf/ext/ke_search/Classes/Domain/Repository/IndexRepository.php in line 42. Requested URL: [myDomain]/typo3/index.php?route=%%2Fmodule%%2Fweb%%2FKeSearchBackendModule&token=--AnonymizedToken--&id=45&

Downgrading to v 4.3.1 helps.

**Comment by bzgaLindner** [comment]
close here and move to actual github
